# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml
#
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

####
cache:
  - key: build-jar
    paths:
      - amparo-backend/build/
    policy: pull

stages:
  - build-test
  - package
  - deploy

services:
  - docker:dind

build-job:
  image: amazoncorretto:17-alpine3.18-jdk
  stage: build-test
  script:
    - ./gradlew clean build
  cache:
    key: build-jar
    paths:
      - amparo-backend/build/
    policy: pull-push

package-job:
  stage: package
#  only:
#    - dev
  script:
    - docker login -u $CI_DOCKER_REGISTRY_USERNAME -p $CI_DOCKER_REGISTRY_PASS
    - docker build -f DockerfileJarCi -t $CI_DOCKER_REGISTRY_USERNAME/amparo-api .
    - docker push $CI_DOCKER_REGISTRY_USERNAME/amparo-api

update-container-job:
  stage: deploy
  needs:
    - package-job
  script:
    - docker login -u $CI_DOCKER_REGISTRY_USERNAME -p $CI_DOCKER_REGISTRY_PASS
    - docker stop amparo-api || true
    - docker rm amparo-api || true
    - docker pull $CI_DOCKER_REGISTRY_USERNAME/amparo-api
    - docker run -d --network amparo-net --name=amparo-api -p 8080:8080 --env SPRING_DATASOURCE_URL=jdbc:postgresql://amparo-database:5432/$CI_DATABASE_NAME --env SPRING_DATASOURCE_USERNAME=$CI_DATABASE_USER --env SPRING_DATASOURCE_PASSWORD=$CI_DATABASE_PASSWORD $CI_DOCKER_REGISTRY_USERNAME/amparo-api