cache:
  key: build-jar
  paths:
    - ./build/libs/amparo-backend*SNAPSHOT.jar
  policy: pull

services:
  - docker:dind

stages:
  - build-test
  - package
  - deploy
  - debug

build-job:
  image: amazoncorretto:17-alpine3.18-jdk
  stage: build-test
  except:
    - debug
  script:
    - ./gradlew clean build
    - echo done
  cache:
    key: build-jar
    paths:
      - ./build/libs/amparo-backend*SNAPSHOT.jar
    policy: pull-push

package-job:
  stage: package
  needs:
    - build-job
  only:
    - dev
    - main
  script:
    - docker login -u $CI_DOCKER_REGISTRY_USERNAME -p $CI_DOCKER_REGISTRY_PASS
    - docker build -f DockerfileJarCi -t $CI_DOCKER_REGISTRY_USERNAME/amparo-api .
    - docker push $CI_DOCKER_REGISTRY_USERNAME/amparo-api

update-container-job:
  stage: deploy
  only:
    - dev
    - main
  needs:
    - package-job
  script:
    - docker login -u $CI_DOCKER_REGISTRY_USERNAME -p $CI_DOCKER_REGISTRY_PASS
    - docker stop amparo-api || true
    - docker rm amparo-api || true
    - docker pull $CI_DOCKER_REGISTRY_USERNAME/amparo-api
    - docker run -d --network amparo-net --name=amparo-api -p 8080:8080 --env SPRING_DATASOURCE_URL=jdbc:postgresql://amparo-database:5432/$CI_DATABASE_NAME --env SPRING_DATASOURCE_USERNAME=$CI_DATABASE_USER --env SPRING_DATASOURCE_PASSWORD=$CI_DATABASE_PASSWORD $CI_DOCKER_REGISTRY_USERNAME/amparo-api

debug-job:

  stage: debug
  only:
    - debug
  script:
    - docker logs --since=1h amparo-api