version: '3'
volumes:
  db-amparo-volume:
services:
  amparo-back:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - amparo-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://amparo-db:5432/amparo-db?user=amparo&password=amparo
  amparo-db:
    image: "postgres:12.3"
    ports:
      - "5432:5432"
    volumes:
      - db-amparo-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=amparo
      - POSTGRES_DB=amparo-db
      - POSTGRES_USER=amparo