INSERT INTO "Medicamento" (ID,NAME) VALUES (1, 'Abacavir (ABC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (2, 'Albuvirtida (ABT)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (3, 'Atazanavir sozinho (ATV)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (4, 'Atazanavir/cobicistate (ATV/c)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (5, 'Atazanavir + ritonavir (ATV/r)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (6, 'Bictegravir/ Emtricitabina/Tenofovir alafenamida (BIC/FTC/TAF)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (7, 'Cabotegravir [oral] (CAB oral)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (8, 'Cabotegravir PrEP [ação prolongada] (CAB LA, PrEP)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (9, 'Cabotegravir/rilpivirina [ação prolongada] (CAB/RPV LA)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (10, 'Dapivirina (DPV, PrEP)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (11, 'Darunavir/cobicistate (DRV/c)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (12, 'Darunavir/Cobicistate/ Emtricitabina/Tenofovir alafenamida (DRV/c/FTC/TAF)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (13, 'Darunavir + ritonavir (DRV/r)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (14, 'Dolutegravir/Abacavir/Lamivudina (DTG/ABC/3TC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (15, 'Dolutegravir (DTG)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (16, 'Dolutegravir/Lamivudina (DTG/3TC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (17, 'Dolutegravir/Rilpivirina (DTG/RPV)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (18, 'Doravirina (DOR)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (19, 'Doravirina/Lamivudina/ Tenofovir-DF (DOR/3TC/TDF)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (20, 'Efavirenz (EFV)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (21, 'Elvitegravir/Cobicistate/ Emtricitabina/Tenofovir alafenamida (EVG/c/FTC/TAF)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (22, 'Elvitegravir/Cobicistate/ Emtricitabina/Tenofovir-DF (EVG/c/FTC/TDF)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (23, 'Entricitabina (FTC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (24, 'Emtricitabine/Tenofovir alafenamide for PrEP (FTC/TAF, PrEP)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (25, 'Emtricitabine/Tenofovir alafenamide (FTC/TAF)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (26, 'Entricitabina/Tenofovir-DF (FTC/TDF, PrEP)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (27, 'Enfuvirtida (ENF, T20)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (28, 'Etravirina (ETR)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (29, 'Fostemsavir (FTR)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (30, 'Ibalizumabe-uiyk (IBA)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (31, 'Lamivudina (3TC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (32, 'Lenacapavir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (33, 'Lopinavir/ritonavir (LPV/r)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (34, 'Maraviroque (MVC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (35, 'Nevirapina (NVP)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (36, 'Raltegravir (RAL)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (37, 'Rilpivirina/ Emtricitabina/Tenofovir alafenamida (RPV/FTC/TAF)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (38, 'Rilpivirina/Emtricitabina/Tenofovir-DF (RPV/FTC/TDF)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (39, 'Rilpivirina (RPV)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (40, 'Ritonavir (RTV)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (41, 'Tenofovir-DF (TDF)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (42, 'Zidovudina (AZT, ZDV)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (43, 'Abatacept');
INSERT INTO "Medicamento" (ID,NAME) VALUES (44, 'Abemaciclibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (45, 'Abiraterona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (46, 'Abrocitinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (47, 'Acalabrutinibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (48, 'Acamprosato');
INSERT INTO "Medicamento" (ID,NAME) VALUES (49, 'Acarbose');
INSERT INTO "Medicamento" (ID,NAME) VALUES (50, 'Acenocumarol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (51, 'Acetato de Ciproterona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (52, 'Acetato de megestrol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (53, 'Acetazolamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (54, 'Aciclovir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (55, 'Ácido Ascórbico (Vitamina C) [em multivitamínicos]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (56, 'Ácido ascórbico (Vitamina C) [sozinho]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (57, 'Ácido clavulânico');
INSERT INTO "Medicamento" (ID,NAME) VALUES (58, 'Ácido fólico [em multivitamínicos]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (59, 'Ácido fólico [sozinho]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (60, 'Ácido mefenâmico');
INSERT INTO "Medicamento" (ID,NAME) VALUES (61, 'Ácido paraminossalicílico');
INSERT INTO "Medicamento" (ID,NAME) VALUES (62, 'Ácido tranexâmico');
INSERT INTO "Medicamento" (ID,NAME) VALUES (63, 'Ácido Ursodesoxicólico');
INSERT INTO "Medicamento" (ID,NAME) VALUES (64, 'Acitretina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (65, 'Adalimumabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (66, 'Adefovir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (67, 'Adrenalina (Epinefrina)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (68, 'Afatinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (69, 'Agomelatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (70, 'Albendazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (71, 'Alcaçuz (Glycyrrhiza glabra)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (72, 'Álcool');
INSERT INTO "Medicamento" (ID,NAME) VALUES (73, 'Alcurônio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (74, 'Alectinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (75, 'Alemtuzumab (Cancer therapy)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (76, 'Alendronic Acid (Alendronate)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (77, 'Alfainterferona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (78, 'Alfentanila');
INSERT INTO "Medicamento" (ID,NAME) VALUES (79, 'Alfuzosina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (80, 'Alho');
INSERT INTO "Medicamento" (ID,NAME) VALUES (81, 'Alirocumabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (82, 'Alisquireno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (83, 'Almotriptana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (84, 'Aloe vera');
INSERT INTO "Medicamento" (ID,NAME) VALUES (85, 'Alogliptina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (86, 'Alopurinol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (87, 'Alosetrona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (88, 'Alpelisib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (89, 'Alprazolam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (90, 'Amantadina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (91, 'Ambrisentana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (92, 'Amicacina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (93, 'Amilorida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (94, 'Aminofilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (95, 'Amiodarona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (96, 'Amissulprida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (97, 'Amitriptilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (98, 'Amivantamab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (99, 'Amodiaquina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (100, 'Amoxicilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (101, 'Ampicilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (102, 'Anakinra');
INSERT INTO "Medicamento" (ID,NAME) VALUES (103, 'Anastrozol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (104, 'Anfetamina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (105, 'Anfotericina B');
INSERT INTO "Medicamento" (ID,NAME) VALUES (106, 'Anidulafungina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (107, 'Anlodipino');
INSERT INTO "Medicamento" (ID,NAME) VALUES (108, 'Antiácidos');
INSERT INTO "Medicamento" (ID,NAME) VALUES (109, 'Antimoniato de meglumina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (110, 'Apalutamide');
INSERT INTO "Medicamento" (ID,NAME) VALUES (111, 'Apixabana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (112, 'Apomorfina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (113, 'Apremilast');
INSERT INTO "Medicamento" (ID,NAME) VALUES (114, 'Aprepitanto');
INSERT INTO "Medicamento" (ID,NAME) VALUES (115, 'Argatroban');
INSERT INTO "Medicamento" (ID,NAME) VALUES (116, 'Aripiprazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (117, 'Artemisinina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (118, 'Asciminib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (119, 'Asenapina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (120, 'Ashwagandha (Withania somnifera)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (121, 'Asparaginase');
INSERT INTO "Medicamento" (ID,NAME) VALUES (122, 'Aspirina (Analgésico)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (123, 'Aspirina (terapia antiplaquetária)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (124, 'Astemizol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (125, 'Atenolol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (126, 'Atezolizumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (127, 'Atomoxetina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (128, 'Atorvastatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (129, 'Atovaquona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (130, 'Atropina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (131, 'Avanafil');
INSERT INTO "Medicamento" (ID,NAME) VALUES (132, 'Avapritinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (133, 'Avelumabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (134, 'Axitinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (135, 'Ayahuasca');
INSERT INTO "Medicamento" (ID,NAME) VALUES (136, 'Azatioprina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (137, 'Azilsartana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (138, 'Azitromicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (139, 'Baclofeno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (140, 'Baricitinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (141, 'Basiliximabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (142, 'Batata africana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (143, 'Bazedoxifeno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (144, 'Beclometasona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (145, 'Bedaquilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (146, 'Belatacepte');
INSERT INTO "Medicamento" (ID,NAME) VALUES (147, 'Belimumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (148, 'Bempedoic acid');
INSERT INTO "Medicamento" (ID,NAME) VALUES (149, 'Benazepril');
INSERT INTO "Medicamento" (ID,NAME) VALUES (150, 'Bendamustine');
INSERT INTO "Medicamento" (ID,NAME) VALUES (151, 'Bendroflumetiazida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (152, 'Benserazida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (153, 'Benzatropine (Benztropine)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (154, 'Benznidazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (155, 'Bepridil');
INSERT INTO "Medicamento" (ID,NAME) VALUES (156, 'Betaistina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (157, 'Betametasona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (158, 'Betrixabana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (159, 'Bevacizumabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (160, 'Bexaroteno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (161, 'Bezafibrato');
INSERT INTO "Medicamento" (ID,NAME) VALUES (162, 'Bicalutamide');
INSERT INTO "Medicamento" (ID,NAME) VALUES (163, 'Binimetinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (164, 'Biperideno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (165, 'Bisacodil');
INSERT INTO "Medicamento" (ID,NAME) VALUES (166, 'Bismuth subsalicylate');
INSERT INTO "Medicamento" (ID,NAME) VALUES (167, 'Bisoprolol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (168, 'Bleomicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (169, 'Blinatumomabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (170, 'Bortezomibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (171, 'Bosentana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (172, 'Bosutinibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (173, 'Brentuximabe vedotina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (174, 'Brigatinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (175, 'Brimonidina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (176, 'Brincidofovir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (177, 'Bromazepam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (178, 'Brometo de aclidínio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (179, 'Brometo de glicopirrônio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (180, 'Brometo de ipratrópio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (181, 'Brometo de tiotrópio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (182, 'Brometo de umeclidínio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (183, 'Budesonida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (184, 'Bulevirtida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (185, 'Bumetanide');
INSERT INTO "Medicamento" (ID,NAME) VALUES (186, 'Bupivacaína');
INSERT INTO "Medicamento" (ID,NAME) VALUES (187, 'Buprenorfina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (188, 'Bupropiona (Amfebutamona)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (189, 'Buspirona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (190, 'Cabazitaxel');
INSERT INTO "Medicamento" (ID,NAME) VALUES (191, 'Cabergolina (mal de Parkinson)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (192, 'Cabergolina (supressão da lactação)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (193, 'Cabozantinibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (194, 'Calcitonina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (195, 'Canabidiol (CBD)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (196, 'Canábis');
INSERT INTO "Medicamento" (ID,NAME) VALUES (197, 'Canagliflozina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (198, 'Canakinumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (199, 'Canamicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (200, 'Candesartana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (201, 'Capecitabina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (202, 'Capmatinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (203, 'Capreomicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (204, 'Captopril');
INSERT INTO "Medicamento" (ID,NAME) VALUES (205, 'Carbamazepina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (206, 'Carbidopa');
INSERT INTO "Medicamento" (ID,NAME) VALUES (207, 'Carbimazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (208, 'Carboplatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (209, 'Cardo-leiteiro (Silybum marianum)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (210, 'Carfilzomib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (211, 'Carvedilol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (212, 'Caspofungina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (213, 'Cefalexina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (214, 'Cefazolina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (215, 'Cefixima');
INSERT INTO "Medicamento" (ID,NAME) VALUES (216, 'Cefotaxima');
INSERT INTO "Medicamento" (ID,NAME) VALUES (217, 'Ceftazidima');
INSERT INTO "Medicamento" (ID,NAME) VALUES (218, 'Ceftriaxona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (219, 'Celecoxibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (220, 'Cemiplimab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (221, 'Cenobamate');
INSERT INTO "Medicamento" (ID,NAME) VALUES (222, 'Ceritinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (223, 'Certolizumab pegol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (224, 'Cetamina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (225, 'Cetirizina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (226, 'Cetoconazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (227, 'Cetuximabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (228, 'Cianocobalamina (Vitamina B12) [em multivitamínicos]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (229, 'Cianocobalamina (vitamina B12) [sozinho]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (230, 'Ciclesonida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (231, 'Ciclofosfamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (232, 'Ciclosporina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (233, 'Ciclosserina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (234, 'Cidofovir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (235, 'Cilazapril');
INSERT INTO "Medicamento" (ID,NAME) VALUES (236, 'Cimetidina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (237, 'Cinacalcet');
INSERT INTO "Medicamento" (ID,NAME) VALUES (238, 'Ciprofloxacino');
INSERT INTO "Medicamento" (ID,NAME) VALUES (239, 'Cisaprida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (240, 'Cisatracúrio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (241, 'Cisplatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (242, 'Citalopram');
INSERT INTO "Medicamento" (ID,NAME) VALUES (243, 'Citarabina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (244, 'Citrato de Cafeína');
INSERT INTO "Medicamento" (ID,NAME) VALUES (245, 'Claritromicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (246, 'Clindamicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (247, 'Clobazam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (248, 'Clobetasol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (249, 'Clofazimina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (250, 'Clofibrato');
INSERT INTO "Medicamento" (ID,NAME) VALUES (251, 'Clomifeno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (252, 'Clomipramina (Clorimipramina)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (253, 'Clonazepam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (254, 'Clonidina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (255, 'Clopidogrel');
INSERT INTO "Medicamento" (ID,NAME) VALUES (256, 'Clorambucila');
INSERT INTO "Medicamento" (ID,NAME) VALUES (257, 'Cloranfenicol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (258, 'Clorazepato');
INSERT INTO "Medicamento" (ID,NAME) VALUES (259, 'Clordiazepóxido');
INSERT INTO "Medicamento" (ID,NAME) VALUES (260, 'Clorfenamina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (261, 'Clormadinona (COC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (262, 'Cloroquina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (263, 'Clorpromazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (264, 'Clortalidona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (265, 'Clotrimazol (pessário, pastilha)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (266, 'Clotrimazol (tópico)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (267, 'Cloxacilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (268, 'Clozapina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (269, 'Cobimetinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (270, 'Cocaína');
INSERT INTO "Medicamento" (ID,NAME) VALUES (271, 'Codeína');
INSERT INTO "Medicamento" (ID,NAME) VALUES (272, 'Cohosh negro, Actaea (Actaea racemosa, Cimicifuga racemosa)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (273, 'Colchicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (274, 'Colecalciferol (Vitamina D3) [em multivitamínicos]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (275, 'Colecalciferol (vitamina D3) [sozinho]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (276, 'Colestiramina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (277, 'Crizotinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (278, 'Cyclizine');
INSERT INTO "Medicamento" (ID,NAME) VALUES (279, 'Dabigatrana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (280, 'Dabrafenib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (281, 'Dacarbazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (282, 'Daclatasvir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (283, 'Dacomitinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (284, 'Dactinomicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (285, 'Dalteparina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (286, 'Dapagliflozina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (287, 'Dapoxetina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (288, 'Dapsona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (289, 'Daptomycin');
INSERT INTO "Medicamento" (ID,NAME) VALUES (290, 'Daratumumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (291, 'Darifenacina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (292, 'Darolutamide');
INSERT INTO "Medicamento" (ID,NAME) VALUES (293, 'Dasatinibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (294, 'Daunorrubicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (295, 'Deferasirox');
INSERT INTO "Medicamento" (ID,NAME) VALUES (296, 'Delamanida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (297, 'Denosumabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (298, 'Desflurano');
INSERT INTO "Medicamento" (ID,NAME) VALUES (299, 'Desipramina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (300, 'Desloratadine');
INSERT INTO "Medicamento" (ID,NAME) VALUES (301, 'Desmopressin');
INSERT INTO "Medicamento" (ID,NAME) VALUES (302, 'Desogestrel (COC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (303, 'Desogestrel (POP)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (304, 'Desvenlafaxina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (305, 'Dexamethasone (doses above 16 mg)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (306, 'Dexamethasone (low dose; 16 mg or less)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (307, 'Dexlansoprazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (308, 'Dexmedetomidina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (309, 'Dextropropoxifeno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (310, 'Di-hidrocodeína');
INSERT INTO "Medicamento" (ID,NAME) VALUES (311, 'Di-Hidroergotamina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (312, 'Diamorfina (diacetilmorfina)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (313, 'Diazepam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (314, 'Diclofenaco');
INSERT INTO "Medicamento" (ID,NAME) VALUES (315, 'Didrogesterona (HRT)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (316, 'Dietilcarbamazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (317, 'Difenidramina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (318, 'Digoxina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (319, 'Diloxanida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (320, 'Diltiazem');
INSERT INTO "Medicamento" (ID,NAME) VALUES (321, 'Dinitrato de isossorbida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (322, 'Dipiridamol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (323, 'Disopiramida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (324, 'Dissulfiram');
INSERT INTO "Medicamento" (ID,NAME) VALUES (325, 'Docetaxel');
INSERT INTO "Medicamento" (ID,NAME) VALUES (326, 'Dofetilida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (327, 'Dolasetrona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (328, 'Domperidona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (329, 'Donepezila');
INSERT INTO "Medicamento" (ID,NAME) VALUES (330, 'Dopamina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (331, 'Doxazosina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (332, 'Doxepina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (333, 'Doxiciclina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (334, 'Doxorrubicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (335, 'Droloxifeno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (336, 'Dronabinol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (337, 'Dronedarone');
INSERT INTO "Medicamento" (ID,NAME) VALUES (338, 'Drospirenona (COC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (339, 'Drospirenona (HRT)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (340, 'Drospirenona (POP)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (341, 'Dulaglutida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (342, 'Duloxetina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (343, 'Dupilumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (344, 'Durvalumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (345, 'Dutasterida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (346, 'Duvelisib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (347, 'Echinacea');
INSERT INTO "Medicamento" (ID,NAME) VALUES (348, 'Ecstasy (MDMA)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (349, 'Edoxabana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (350, 'Efedrina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (351, 'Eflornitina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (352, 'Elbasvir/Grazoprevir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (353, 'Eletriptano');
INSERT INTO "Medicamento" (ID,NAME) VALUES (354, 'Elotuzumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (355, 'Eltrombopague');
INSERT INTO "Medicamento" (ID,NAME) VALUES (356, 'Empagliflozina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (357, 'Enalapril');
INSERT INTO "Medicamento" (ID,NAME) VALUES (358, 'Enasidenib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (359, 'Encorafenib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (360, 'Enflurano');
INSERT INTO "Medicamento" (ID,NAME) VALUES (361, 'Enfortumab vedotin');
INSERT INTO "Medicamento" (ID,NAME) VALUES (362, 'Enoxaparina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (363, 'Entecavir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (364, 'Entrectinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (365, 'Enzalutamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (366, 'Epirrubicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (367, 'Eplerenona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (368, 'Epoprostenol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (369, 'Eprosartana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (370, 'Eptinezumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (371, 'Erdafitinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (372, 'Erenumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (373, 'Ergometrina (Ergonovina)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (374, 'Ergotamina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (375, 'Eribulin');
INSERT INTO "Medicamento" (ID,NAME) VALUES (376, 'Eritromicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (377, 'Erlotinibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (378, 'Ertapeném');
INSERT INTO "Medicamento" (ID,NAME) VALUES (379, 'Erva São João');
INSERT INTO "Medicamento" (ID,NAME) VALUES (380, 'Escitalopram');
INSERT INTO "Medicamento" (ID,NAME) VALUES (381, 'Eslicarbazepina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (382, 'Esomeprazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (383, 'Espectinomicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (384, 'Espironolactona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (385, 'Estanozolol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (386, 'Estazolam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (387, 'Estibogluconato de sódio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (388, 'Estradiol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (389, 'Estramustina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (390, 'Estreptomicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (391, 'Estreptoquinase');
INSERT INTO "Medicamento" (ID,NAME) VALUES (392, 'Estrogênios conjugados');
INSERT INTO "Medicamento" (ID,NAME) VALUES (393, 'Etambutol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (394, 'Etanercept');
INSERT INTO "Medicamento" (ID,NAME) VALUES (395, 'Etidocaína');
INSERT INTO "Medicamento" (ID,NAME) VALUES (396, 'Etinilestradiol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (397, 'Etionamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (398, 'Etonogestrel (anel vaginal)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (399, 'Etonogestrel (implante)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (400, 'Etoposídeo');
INSERT INTO "Medicamento" (ID,NAME) VALUES (401, 'Etossuximida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (402, 'Eucalyptus globulus');
INSERT INTO "Medicamento" (ID,NAME) VALUES (403, 'Everolimo');
INSERT INTO "Medicamento" (ID,NAME) VALUES (404, 'Evolocumabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (405, 'Exemestano');
INSERT INTO "Medicamento" (ID,NAME) VALUES (406, 'Exenatida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (407, 'Extrato de chá verde (Camellia sinensis)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (408, 'Ezetimiba');
INSERT INTO "Medicamento" (ID,NAME) VALUES (409, 'Famotidina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (410, 'Fampridina (Dalfampridina)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (411, 'Fanciclovir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (412, 'Favipiravir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (413, 'Fedratinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (414, 'Felodipino');
INSERT INTO "Medicamento" (ID,NAME) VALUES (415, 'Femprocumona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (416, 'Fenciclidina (PCP)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (417, 'Fenelzina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (418, 'Fenitoína');
INSERT INTO "Medicamento" (ID,NAME) VALUES (419, 'Fenobarbital (Fenobarbitona)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (420, 'Fenofibrato');
INSERT INTO "Medicamento" (ID,NAME) VALUES (421, 'Fentanila');
INSERT INTO "Medicamento" (ID,NAME) VALUES (422, 'Fesoterodina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (423, 'Fexofenadina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (424, 'Filgrastim');
INSERT INTO "Medicamento" (ID,NAME) VALUES (425, 'Finasterida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (426, 'Fitomenadiona (Vitamina K) [em multivitamínicos]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (427, 'Fitomenadiona (Vitamina K) [sozinha]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (428, 'Flecainida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (429, 'Flibanserina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (430, 'Flucitosina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (431, 'Flucloxacilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (432, 'Fluconazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (433, 'Fludarabina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (434, 'Fludrocortisona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (435, 'Flufenazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (436, 'Flunisolida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (437, 'Flunitrazepam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (438, 'Fluocinolona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (439, 'Fluoruracila');
INSERT INTO "Medicamento" (ID,NAME) VALUES (440, 'Fluoxetina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (441, 'Flupentixol (Flupenthixol)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (442, 'Flurazepam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (443, 'Flutamide');
INSERT INTO "Medicamento" (ID,NAME) VALUES (444, 'Fluticasona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (445, 'Fluvastatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (446, 'Fluvoxamina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (447, 'Folinato de cálcio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (448, 'Fondaparinux');
INSERT INTO "Medicamento" (ID,NAME) VALUES (449, 'Formestano');
INSERT INTO "Medicamento" (ID,NAME) VALUES (450, 'Formoterol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (451, 'Foscarnete');
INSERT INTO "Medicamento" (ID,NAME) VALUES (452, 'Fosfomycin');
INSERT INTO "Medicamento" (ID,NAME) VALUES (453, 'Fosinopril');
INSERT INTO "Medicamento" (ID,NAME) VALUES (454, 'Fostamatinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (455, 'Fremanezumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (456, 'Frovatriptan');
INSERT INTO "Medicamento" (ID,NAME) VALUES (457, 'Fulvestrant');
INSERT INTO "Medicamento" (ID,NAME) VALUES (458, 'Fumarato ferroso');
INSERT INTO "Medicamento" (ID,NAME) VALUES (459, 'Furosemida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (460, 'Gabapentina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (461, 'Galcanezumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (462, 'Ganciclovir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (463, 'Gefitinibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (464, 'Gencitabina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (465, 'Genfibrozila');
INSERT INTO "Medicamento" (ID,NAME) VALUES (466, 'Gengibre (Zingiber officinale)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (467, 'Gentamicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (468, 'Gestodeno (COC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (469, 'GHB (gama-hidroxibutirato)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (470, 'Gilteritinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (471, 'Ginkgo biloba');
INSERT INTO "Medicamento" (ID,NAME) VALUES (472, 'Ginseng (Panax ginseng, Panax quinquefolis)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (473, 'Glasdegib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (474, 'Glecaprevir/Pibrentasvir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (475, 'Glibenclamida (Gliburida)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (476, 'Gliclazida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (477, 'Glimepirida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (478, 'Glipizida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (479, 'Globulina Antitimocítica');
INSERT INTO "Medicamento" (ID,NAME) VALUES (480, 'Glucose monohydrate (IV)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (481, 'Golimumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (482, 'Gosserrelina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (483, 'Granisetrona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (484, 'Griseofulvina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (485, 'Guggulsterona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (486, 'Halofantrina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (487, 'Haloperidol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (488, 'Halotano');
INSERT INTO "Medicamento" (ID,NAME) VALUES (489, 'Heparina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (490, 'Heroína');
INSERT INTO "Medicamento" (ID,NAME) VALUES (491, 'Hidralazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (492, 'Hidroclorotiazida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (493, 'Hidrocodona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (494, 'Hidrocortisona (oral)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (495, 'Hidrocortisona (tópico)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (496, 'Hidromorfona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (497, 'Hidroxicloroquina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (498, 'Hidroxizina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (499, 'Homeopathic remedies');
INSERT INTO "Medicamento" (ID,NAME) VALUES (500, 'Hydroxycarbamide (Hydroxyurea)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (501, 'Hyoscine (Scopolamine)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (502, 'Hyoscine butylbromide (Butylscopolamine)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (503, 'Hyoscine hydrobromide (Scopolamine hydrobromide)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (504, 'Ibandronic acid (Ibandronate)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (505, 'Ibrutinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (506, 'Ibuprofeno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (507, 'Icosapent ethyl');
INSERT INTO "Medicamento" (ID,NAME) VALUES (508, 'Idelalisib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (509, 'Ifosfamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (510, 'Iloperidona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (511, 'Iloprosta');
INSERT INTO "Medicamento" (ID,NAME) VALUES (512, 'Imatinibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (513, 'Imipeném/Cilastatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (514, 'Imipramina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (515, 'Indacaterol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (516, 'Indapamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (517, 'Indometacin (Indomethacin)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (518, 'Infigratinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (519, 'Infliximab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (520, 'Inotuzumab ozogamicin');
INSERT INTO "Medicamento" (ID,NAME) VALUES (521, 'Insulina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (522, 'Interleucina 2 (Aldesleucina)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (523, 'Inula racemosa');
INSERT INTO "Medicamento" (ID,NAME) VALUES (524, 'Iodo [em multivitamínicos]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (525, 'Iodo [sozinho]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (526, 'Ioimbina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (527, 'Ipilimumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (528, 'Irbesartana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (529, 'Irinotecano');
INSERT INTO "Medicamento" (ID,NAME) VALUES (530, 'Isavuconazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (531, 'Isoflurano');
INSERT INTO "Medicamento" (ID,NAME) VALUES (532, 'Isoniazida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (533, 'Isosorbide mononitrate');
INSERT INTO "Medicamento" (ID,NAME) VALUES (534, 'Isotretinoína');
INSERT INTO "Medicamento" (ID,NAME) VALUES (535, 'Ispaghula husk');
INSERT INTO "Medicamento" (ID,NAME) VALUES (536, 'Itraconazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (537, 'Ivabradina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (538, 'Ivermectina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (539, 'Ivosidenib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (540, 'Ixazomib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (541, 'Ixekizumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (542, 'Ketoprofen');
INSERT INTO "Medicamento" (ID,NAME) VALUES (543, 'Ketorolac');
INSERT INTO "Medicamento" (ID,NAME) VALUES (544, 'Labetalol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (545, 'Lacidipino');
INSERT INTO "Medicamento" (ID,NAME) VALUES (546, 'Lacosamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (547, 'Lactulose');
INSERT INTO "Medicamento" (ID,NAME) VALUES (548, 'Lamotrigina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (549, 'Lansoprazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (550, 'Lapatinibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (551, 'Larotrectinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (552, 'Ledipasvir/Sofosbuvir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (553, 'Leflunomide');
INSERT INTO "Medicamento" (ID,NAME) VALUES (554, 'Lenalidomida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (555, 'Lenvatinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (556, 'Lercanidipino');
INSERT INTO "Medicamento" (ID,NAME) VALUES (557, 'Letermovir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (558, 'Letrozole');
INSERT INTO "Medicamento" (ID,NAME) VALUES (559, 'Leuprorrelina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (560, 'Levamisol (Ergamisol)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (561, 'Levedura de arroz vermelho');
INSERT INTO "Medicamento" (ID,NAME) VALUES (562, 'Levetiracetam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (563, 'Levocetirizina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (564, 'Levodopa');
INSERT INTO "Medicamento" (ID,NAME) VALUES (565, 'Levofloxacino');
INSERT INTO "Medicamento" (ID,NAME) VALUES (566, 'Levomepromazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (567, 'Levonorgestrel (COC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (568, 'Levonorgestrel (Contraceptivo de Emergência)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (569, 'Levonorgestrel (HRT)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (570, 'Levonorgestrel (implante)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (571, 'Levonorgestrel (IUD)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (572, 'Levonorgestrel (POP)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (573, 'Levotiroxina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (574, 'Lidocaína (Lignocaína)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (575, 'Linagliptina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (576, 'Linezolida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (577, 'Liraglutida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (578, 'Lisdexamfetamine');
INSERT INTO "Medicamento" (ID,NAME) VALUES (579, 'Lisinopril');
INSERT INTO "Medicamento" (ID,NAME) VALUES (580, 'Lítio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (581, 'Lomitapide');
INSERT INTO "Medicamento" (ID,NAME) VALUES (582, 'Lomustine');
INSERT INTO "Medicamento" (ID,NAME) VALUES (583, 'Loperamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (584, 'Loratadina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (585, 'Lorazepam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (586, 'Lorlatinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (587, 'Lormetazepam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (588, 'Losartana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (589, 'Lovastatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (590, 'LSD (Dietilamida do ácido lisérgico)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (591, 'Lumefantrina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (592, 'Lúpulos (Humulus lupulus)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (593, 'Lurasidone');
INSERT INTO "Medicamento" (ID,NAME) VALUES (594, 'Macitentana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (595, 'Macrogol (Polyethylene glycol, PEG 3350, PEG 4000)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (596, 'Manitol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (597, 'Maprotilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (598, 'Maribavir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (599, 'Mebendazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (600, 'Mebeverine');
INSERT INTO "Medicamento" (ID,NAME) VALUES (601, 'Medroxiprogesterona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (602, 'Medroxiprogesterona (injeção de depósito)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (603, 'Medroxiprogesterona (TRH)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (604, 'Mefedrona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (605, 'Mefloquina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (606, 'Melarsoprol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (607, 'Melatonin');
INSERT INTO "Medicamento" (ID,NAME) VALUES (608, 'Meloxicam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (609, 'Memantina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (610, 'Mentol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (611, 'Mercaptopurina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (612, 'Meropeném');
INSERT INTO "Medicamento" (ID,NAME) VALUES (613, 'Mesalazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (614, 'Mesna');
INSERT INTO "Medicamento" (ID,NAME) VALUES (615, 'Metadona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (616, 'Metanfetamina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (617, 'Metformina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (618, 'Methylergometrine (Methylergonovine)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (619, 'Metildopa');
INSERT INTO "Medicamento" (ID,NAME) VALUES (620, 'Metilfenidato');
INSERT INTO "Medicamento" (ID,NAME) VALUES (621, 'Metilprednisolona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (622, 'Metoclopramida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (623, 'Metolazona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (624, 'Metoprolol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (625, 'Metotrexato (Ametopterina)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (626, 'Metronidazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (627, 'Mexiletina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (628, 'Mianserina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (629, 'Micofenolato');
INSERT INTO "Medicamento" (ID,NAME) VALUES (630, 'Miconazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (631, 'Midazolam (oral)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (632, 'Midazolam (parenteral)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (633, 'Midodrine');
INSERT INTO "Medicamento" (ID,NAME) VALUES (634, 'Midostaurin');
INSERT INTO "Medicamento" (ID,NAME) VALUES (635, 'Mifepristona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (636, 'Milnaciprana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (637, 'Miltefosina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (638, 'Minaxolona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (639, 'Minoxidil');
INSERT INTO "Medicamento" (ID,NAME) VALUES (640, 'Minoxidil (Topical)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (641, 'Mirabegrona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (642, 'Mirtazapina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (643, 'Misoprostol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (644, 'Mitotane');
INSERT INTO "Medicamento" (ID,NAME) VALUES (645, 'Mitoxantrona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (646, 'Mobocertinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (647, 'Modafinila');
INSERT INTO "Medicamento" (ID,NAME) VALUES (648, 'Molnupiravir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (649, 'Mometasona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (650, 'Montelucaste');
INSERT INTO "Medicamento" (ID,NAME) VALUES (651, 'Morfina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (652, 'Moxifloxacino');
INSERT INTO "Medicamento" (ID,NAME) VALUES (653, 'Moxonidina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (654, 'Mucuna pruriens');
INSERT INTO "Medicamento" (ID,NAME) VALUES (655, 'Multivitaminas');
INSERT INTO "Medicamento" (ID,NAME) VALUES (656, 'Naftidrofurila');
INSERT INTO "Medicamento" (ID,NAME) VALUES (657, 'Naloxona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (658, 'Naltrexona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (659, 'Nandrolona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (660, 'Naproxeno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (661, 'Naratriptan');
INSERT INTO "Medicamento" (ID,NAME) VALUES (662, 'Nateglinida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (663, 'Nebivolol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (664, 'Necitumumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (665, 'Nefazodona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (666, 'Neostigmina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (667, 'Neratinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (668, 'Nicardipino');
INSERT INTO "Medicamento" (ID,NAME) VALUES (669, 'Niclosamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (670, 'Nicorandil');
INSERT INTO "Medicamento" (ID,NAME) VALUES (671, 'Nicotina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (672, 'Nicotinamida (Niacinamida) [em multivitamínicos]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (673, 'Nicotinamida (Niacinamida) [sozinho]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (674, 'Nifedipino');
INSERT INTO "Medicamento" (ID,NAME) VALUES (675, 'Nifurtimox');
INSERT INTO "Medicamento" (ID,NAME) VALUES (676, 'Nilotinibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (677, 'Nilutamide');
INSERT INTO "Medicamento" (ID,NAME) VALUES (678, 'Nimesulida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (679, 'Nintedanib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (680, 'Niraparib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (681, 'Nirmatrelvir/ritonavir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (682, 'Nisoldipino');
INSERT INTO "Medicamento" (ID,NAME) VALUES (683, 'Nistatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (684, 'Nitazoxanide');
INSERT INTO "Medicamento" (ID,NAME) VALUES (685, 'Nitrendipino');
INSERT INTO "Medicamento" (ID,NAME) VALUES (686, 'Nitrofurantoína');
INSERT INTO "Medicamento" (ID,NAME) VALUES (687, 'Nitroprusseto de sódio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (688, 'Nivolumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (689, 'Norelgestromina (adesivo)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (690, 'Noretisterona [Noretindrona] (COC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (691, 'Noretisterona [Noretindrona] (HRT)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (692, 'Noretisterona [Noretindrona] (Injeção de Depósito IM)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (693, 'Noretisterona [Noretindrona] (POP)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (694, 'Norgestimato (COC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (695, 'Norgestimato (TRH)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (696, 'Norgestrel (COC)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (697, 'Norgestrel (HRT)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (698, 'Nortriptilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (699, 'Noz de Malabar (Justicia adhatoda, Adhatoda vasica)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (700, 'Obinutuzumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (701, 'Octreotide');
INSERT INTO "Medicamento" (ID,NAME) VALUES (702, 'Ofatumumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (703, 'Ofloxacino');
INSERT INTO "Medicamento" (ID,NAME) VALUES (704, 'Olanzapina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (705, 'Olaparib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (706, 'Olaratumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (707, 'Óleos de Peixe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (708, 'Olmesartana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (709, 'Olodaterol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (710, 'Ombitasvir/Paritaprevir/r');
INSERT INTO "Medicamento" (ID,NAME) VALUES (711, 'Ombitasvir/Paritaprevir/r + Dasabuvir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (712, 'Omega-3 fatty acids');
INSERT INTO "Medicamento" (ID,NAME) VALUES (713, 'Omega-3 fatty acids [in multivitamins]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (714, 'Omeprazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (715, 'Ondansetrona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (716, 'Orlistate');
INSERT INTO "Medicamento" (ID,NAME) VALUES (717, 'Orphenadrine');
INSERT INTO "Medicamento" (ID,NAME) VALUES (718, 'Oseltamivir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (719, 'Osimertinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (720, 'Oxaliplatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (721, 'Oxamniquina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (722, 'Oxandrolona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (723, 'Oxazepam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (724, 'Oxcarbazepina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (725, 'Oxibutinina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (726, 'Oxicodona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (727, 'Óxido nitroso');
INSERT INTO "Medicamento" (ID,NAME) VALUES (728, 'Oxitocina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (729, 'Oxprenolol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (730, 'Paclitaxel');
INSERT INTO "Medicamento" (ID,NAME) VALUES (731, 'Palbociclib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (732, 'Paliperidona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (733, 'Panitumumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (734, 'Panobinostat');
INSERT INTO "Medicamento" (ID,NAME) VALUES (735, 'Pantoprazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (736, 'Paracetamol (Acetaminofeno)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (737, 'Paromomicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (738, 'Paroxetina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (739, 'Pazopanibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (740, 'Peginterferon alfa-2a');
INSERT INTO "Medicamento" (ID,NAME) VALUES (741, 'Peginterferon alfa-2b');
INSERT INTO "Medicamento" (ID,NAME) VALUES (742, 'Pembrolizumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (743, 'Pemetrexed');
INSERT INTO "Medicamento" (ID,NAME) VALUES (744, 'Pemigatinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (745, 'Penicilamina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (746, 'Penicilinas');
INSERT INTO "Medicamento" (ID,NAME) VALUES (747, 'Pentamidina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (748, 'Pentoxifilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (749, 'Perazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (750, 'Perfenazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (751, 'Periciazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (752, 'Perindopril');
INSERT INTO "Medicamento" (ID,NAME) VALUES (753, 'Pertuzumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (754, 'Petidina (Meperidina)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (755, 'Pexidartinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (756, 'Pilocarpina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (757, 'Pimenta-de-java (Piper Cubeba)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (758, 'Pimozida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (759, 'Pindolol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (760, 'Pioglitazona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (761, 'Piperacilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (762, 'Piperaquina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (763, 'Pipotiazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (764, 'Pirantel');
INSERT INTO "Medicamento" (ID,NAME) VALUES (765, 'Pirazinamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (766, 'Piridostigmina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (767, 'Piridoxina (Vitamina B6) [em multivitamínicos]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (768, 'Piridoxina (Vitamina B6) [sozinha]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (769, 'Pirimetamina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (770, 'Piroxicam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (771, 'Pitavastatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (772, 'Pizotifen');
INSERT INTO "Medicamento" (ID,NAME) VALUES (773, 'Polatuzumabe vedotina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (774, 'Pomalidomide');
INSERT INTO "Medicamento" (ID,NAME) VALUES (775, 'Ponatinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (776, 'Poppers (Nitrito de amila)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (777, 'Posaconazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (778, 'Potássio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (779, 'Pralsetinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (780, 'Pramipexol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (781, 'Prasugrel');
INSERT INTO "Medicamento" (ID,NAME) VALUES (782, 'Pravastatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (783, 'Praziquantel');
INSERT INTO "Medicamento" (ID,NAME) VALUES (784, 'Prazosina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (785, 'Prednisolona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (786, 'Prednisona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (787, 'Pregabalina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (788, 'Pretomanid');
INSERT INTO "Medicamento" (ID,NAME) VALUES (789, 'Primaquina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (790, 'Primidona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (791, 'Probenecida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (792, 'Procarbazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (793, 'Proclorperazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (794, 'Procyclidine');
INSERT INTO "Medicamento" (ID,NAME) VALUES (795, 'Progesterona (TRH)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (796, 'Proguanil');
INSERT INTO "Medicamento" (ID,NAME) VALUES (797, 'Prometazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (798, 'Propafenona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (799, 'Propiltiouracila');
INSERT INTO "Medicamento" (ID,NAME) VALUES (800, 'Propofol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (801, 'Propranolol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (802, 'Prucaloprida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (803, 'Psyllium husk');
INSERT INTO "Medicamento" (ID,NAME) VALUES (804, 'Quercetina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (805, 'Quetiapina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (806, 'Quinapril');
INSERT INTO "Medicamento" (ID,NAME) VALUES (807, 'Quinidina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (808, 'Quinina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (809, 'Rabeprazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (810, 'Raiz de Ouro (Hydrastis canadensis)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (811, 'Raloxifene');
INSERT INTO "Medicamento" (ID,NAME) VALUES (812, 'Ramipril');
INSERT INTO "Medicamento" (ID,NAME) VALUES (813, 'Ranelato de estrôncio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (814, 'Ranitidina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (815, 'Ranolazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (816, 'Rasagilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (817, 'Reboxetina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (818, 'Regorafenib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (819, 'Remdesivir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (820, 'Repaglinida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (821, 'Retinol (Vitamina A) [em multivitamínicos]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (822, 'Retinol (Vitamina A) [sozinho]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (823, 'Ribavirina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (824, 'Ribociclib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (825, 'Riboflavina (Vitamina B2) [em multivitamínicos]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (826, 'Riboflavina (Vitamina B2) [sozinha]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (827, 'Rifabutina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (828, 'Rifampicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (829, 'Rifapentina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (830, 'Rifaximina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (831, 'Rimantadina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (832, 'Riociguate');
INSERT INTO "Medicamento" (ID,NAME) VALUES (833, 'Risankizumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (834, 'Risedronic acid (Risedronate)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (835, 'Risperidona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (836, 'Rituximabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (837, 'Rivaroxabana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (838, 'Rizatriptana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (839, 'Rocurônio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (840, 'Roflumilaste');
INSERT INTO "Medicamento" (ID,NAME) VALUES (841, 'Ropinirol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (842, 'Rosiglitazona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (843, 'Rosuvastatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (844, 'Rucaparib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (845, 'Ruxolitinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (846, 'Ruxolitinib (topical)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (847, 'Sabal serrulata (Serenoa repens)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (848, 'Sacubitril');
INSERT INTO "Medicamento" (ID,NAME) VALUES (849, 'Salbutamol (Albuterol)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (850, 'Salmeterol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (851, 'Sarilumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (852, 'Saxagliptina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (853, 'Secukinumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (854, 'Selexipague');
INSERT INTO "Medicamento" (ID,NAME) VALUES (855, 'Selpercatinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (856, 'Semaglutida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (857, 'Senna');
INSERT INTO "Medicamento" (ID,NAME) VALUES (858, 'Sertralina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (859, 'Sevelamer');
INSERT INTO "Medicamento" (ID,NAME) VALUES (860, 'Sevoflurano');
INSERT INTO "Medicamento" (ID,NAME) VALUES (861, 'Sildenafila (Disfunção Eréctil)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (862, 'Sildenafila (Hipertensão Arterial Pulmonar)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (863, 'Silodosina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (864, 'Simeprevir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (865, 'Sinvastatina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (866, 'Sirolimo');
INSERT INTO "Medicamento" (ID,NAME) VALUES (867, 'Sitagliptina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (868, 'Sodium valproate');
INSERT INTO "Medicamento" (ID,NAME) VALUES (869, 'Sofosbuvir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (870, 'Sofosbuvir/Velpatasvir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (871, 'Sofosbuvir/Velpatasvir/Voxilaprevir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (872, 'Solifenacina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (873, 'Sorafenibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (874, 'Sotalol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (875, 'Sotorasib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (876, 'Sotrovimabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (877, 'Suco de laranja de Sevilha');
INSERT INTO "Medicamento" (ID,NAME) VALUES (878, 'Suco de toronja');
INSERT INTO "Medicamento" (ID,NAME) VALUES (879, 'Sucralfate');
INSERT INTO "Medicamento" (ID,NAME) VALUES (880, 'Sufentanila');
INSERT INTO "Medicamento" (ID,NAME) VALUES (881, 'Sulfadiazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (882, 'Sulfadoxina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (883, 'Sulfassalazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (884, 'Sulfato de protamina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (885, 'Sulpirida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (886, 'Sumatriptana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (887, 'Sunitinibe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (888, 'Suplementos de Cálcio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (889, 'Suplementos de ferro (infusão/injeção)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (890, 'Suplementos de ferro (oral)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (891, 'Suplementos de Magnésio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (892, 'Suramina sódica');
INSERT INTO "Medicamento" (ID,NAME) VALUES (893, 'Suxametônio (Succinilcolina)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (894, 'Tacrolimo');
INSERT INTO "Medicamento" (ID,NAME) VALUES (895, 'Tadalafila (Disfunção Eréctil)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (896, 'Tadalafila (Hipertensão Arterial Pulmonar)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (897, 'Talazoparib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (898, 'Talidomida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (899, 'Tamoxifeno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (900, 'Tansulosina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (901, 'Tapentadol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (902, 'Tazobactam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (903, 'Tecovirimat');
INSERT INTO "Medicamento" (ID,NAME) VALUES (904, 'Tegafur/ Gimeracil/ Oteracil');
INSERT INTO "Medicamento" (ID,NAME) VALUES (905, 'Telbivudina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (906, 'Telitromicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (907, 'Telmisartana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (908, 'Temazepam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (909, 'Tenofovir alafenamida (HBV)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (910, 'Tensirolimo');
INSERT INTO "Medicamento" (ID,NAME) VALUES (911, 'Teofilina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (912, 'Terazosina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (913, 'Terbinafina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (914, 'Terbutalina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (915, 'Terfenadina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (916, 'Terlipressin');
INSERT INTO "Medicamento" (ID,NAME) VALUES (917, 'Tesamorelin');
INSERT INTO "Medicamento" (ID,NAME) VALUES (918, 'Testosterona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (919, 'Tetracaína');
INSERT INTO "Medicamento" (ID,NAME) VALUES (920, 'Tetraciclina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (921, 'Tiagabina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (922, 'Tiamina (Vitamina B1) [em multivitamínicos]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (923, 'Tiamina (Vitamina B1) [sozinha]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (924, 'Tiaprida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (925, 'Tibolona (TRH)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (926, 'Ticagrelor');
INSERT INTO "Medicamento" (ID,NAME) VALUES (927, 'Timolol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (928, 'Tinidazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (929, 'Tinzaparin');
INSERT INTO "Medicamento" (ID,NAME) VALUES (930, 'Tiopental');
INSERT INTO "Medicamento" (ID,NAME) VALUES (931, 'Tioridazina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (932, 'Tirzepatide');
INSERT INTO "Medicamento" (ID,NAME) VALUES (933, 'Tivozanib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (934, 'Tixagevimabe/Cilgavimabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (935, 'Tizanidina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (936, 'Tocilizumabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (937, 'Tocoferol (Vitamina E) [em multivitamínicos]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (938, 'Tocoferol (Vitamina E) [sozinho]');
INSERT INTO "Medicamento" (ID,NAME) VALUES (939, 'Tofacitinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (940, 'Tolbutamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (941, 'Tolterodina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (942, 'Topiramato');
INSERT INTO "Medicamento" (ID,NAME) VALUES (943, 'Topotecana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (944, 'Torasemida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (945, 'Toremifeno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (946, 'Tramadol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (947, 'Trametinib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (948, 'Trandolapril');
INSERT INTO "Medicamento" (ID,NAME) VALUES (949, 'Tranilcipromina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (950, 'Trastuzumabe');
INSERT INTO "Medicamento" (ID,NAME) VALUES (951, 'Trastuzumabe emtansina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (952, 'Trazodona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (953, 'Treprostinila');
INSERT INTO "Medicamento" (ID,NAME) VALUES (954, 'Triancinolona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (955, 'Triantereno');
INSERT INTO "Medicamento" (ID,NAME) VALUES (956, 'Triazolam');
INSERT INTO "Medicamento" (ID,NAME) VALUES (957, 'Triclabendazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (958, 'Trifluridine/Tipiracil');
INSERT INTO "Medicamento" (ID,NAME) VALUES (959, 'Trimetoprima/Sulfametoxazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (960, 'Trimipramina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (961, 'Trinitrato de glicerina (nitroglicerina)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (962, 'Triptorrelina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (963, 'Tróspio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (964, 'Tumérico (Curcuma longa)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (965, 'Ulipristal');
INSERT INTO "Medicamento" (ID,NAME) VALUES (966, 'Unha de gato (Uncaria tomentosa)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (967, 'Ustekinumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (968, 'Valaciclovir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (969, 'Valeriana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (970, 'Valganciclovir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (971, 'Valproate semisodium (Divalproex sodium)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (972, 'Valproic acid');
INSERT INTO "Medicamento" (ID,NAME) VALUES (973, 'Valsartana');
INSERT INTO "Medicamento" (ID,NAME) VALUES (974, 'Vancomicina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (975, 'Vardenafila (Disfunção Eréctil)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (976, 'Vareniclina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (977, 'Varfarina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (978, 'Vecurônio');
INSERT INTO "Medicamento" (ID,NAME) VALUES (979, 'Vedolizumab');
INSERT INTO "Medicamento" (ID,NAME) VALUES (980, 'Vemurafenib');
INSERT INTO "Medicamento" (ID,NAME) VALUES (981, 'Venetoclax');
INSERT INTO "Medicamento" (ID,NAME) VALUES (982, 'Venlafaxina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (983, 'Verapamil');
INSERT INTO "Medicamento" (ID,NAME) VALUES (984, 'Vigabatrina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (985, 'Vilanterol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (986, 'Vildagliptina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (987, 'Vimblastina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (988, 'Vincristina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (989, 'Vinorelbina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (990, 'Voriconazol');
INSERT INTO "Medicamento" (ID,NAME) VALUES (991, 'Vorinostate');
INSERT INTO "Medicamento" (ID,NAME) VALUES (992, 'Vortioxetina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (993, 'Xipamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (994, 'Zaleplona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (995, 'Zanamivir');
INSERT INTO "Medicamento" (ID,NAME) VALUES (996, 'Zinc');
INSERT INTO "Medicamento" (ID,NAME) VALUES (997, 'Ziprasidona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (998, 'Zoledronic acid (Zoledronate)');
INSERT INTO "Medicamento" (ID,NAME) VALUES (999, 'Zolmitriptano');
INSERT INTO "Medicamento" (ID,NAME) VALUES (1000, 'Zolpidem');
INSERT INTO "Medicamento" (ID,NAME) VALUES (1001, 'Zonisamida');
INSERT INTO "Medicamento" (ID,NAME) VALUES (1002, 'Zopiclona');
INSERT INTO "Medicamento" (ID,NAME) VALUES (1003, 'Zotepina');
INSERT INTO "Medicamento" (ID,NAME) VALUES (1004, 'Zuclopentixol');